language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer install --prefer-source

scripts:
    - vendor/bin/phpunit

notifications:
    - email: chris@neoxygen.io

